### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/hci-solutions#14]
Page: [NetApp HCI for DevOps](https://docs.netapp.com/us-en/hci-solutions/nhci_devops_cicd.html)

Link in the following bullet is dead:

* `Deploy an application on a NetApp HCI cluster using curated NKS Helm charts: Blog`

**Comment by kevin-hoke** [comment]
This issue should be resolved with the removal of the source from the github repository
