### ISSUE TITLE
Commit info in page content

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/hci-solutions#31]
It seems it's from a commit by @kevin-hoke (https://github.com/NetAppDocs/hci-solutions/pull/28).
This appears in 2 pages (not just in the one below but also in [here](https://github.com/NetAppDocs/hci-solutions/blob/64d5ab19bb912ff80ced0eed211e552a4aeca6c0/hcicaci_architecture.adoc))

![image](https://user-images.githubusercontent.com/16622642/92339963-2d86a100-f0eb-11ea-922e-0fe380aabb93.png)

Page: [VMware vSphere: NetApp HCI with Cisco ACI](https://docs.netapp.com/us-en/hci-solutions/hcicaci_vmware_vsphere__netapp_hci_with_cisco_aci.html)

**Comment by kevin-hoke** [comment]
Thank you for the feedback.  This issue should be resolved.
