### ISSUE TITLE
Link to NDE 1.6 Deployment Guide should point to HTML version

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/hci-solutions#39]
Page: [3. Deploy NetApp HCI with the NetApp Deployment Engine](https://docs.netapp.com/us-en/hci-solutions/anthos_task_deploy_netapp_hci.html)

In this topic, there is a link to the PDF version of the HCI Deployment Guide. Our best practice is to always link to the HTML when it is available.

Please consider replacing the link to the PDF with the following link:

https://docs.netapp.com/hci/topic/com.netapp.doc.hci-ude-16p1/home.html

**Comment by ntap-bmegan** [comment]
@netapp-dorianh - Please update status or close if work is complete.

**Comment by ntap-bmegan** [comment]
@netapp-dorianh - What is the status of this issue?
