### ISSUE TITLE
Easy Scale with Cisco AVE

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/hci-solutions#43]
If Cisco AVE is configured, would NDE Easy Scale to expand the cluster require additional steps? 
Can this information be added to the page?

Page: [VMware vSphere: NetApp HCI with Cisco ACI](https://docs.netapp.com/us-en/hci-solutions/hcicaci_vmware_vsphere__netapp_hci_with_cisco_aci.html)

**Comment by kulkarnn** [comment]
Thankyou Sean. The updated documentation in netapp-solutions now outlines NDE Easy Scale procedure for VMware deployments. You can find it at - https://docs.netapp.com/us-en/netapp-solutions/hcicaci_netapp_hci_with_cisco_aci.html

**Comment by scaleoutsean** [comment]
Thank you. It seems this issue can be closed now.
