### ISSUE TITLE
Global issue: Graphics in this document should not contain "NetApp Confidential"

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/hci-solutions#51]
Page: [NVA-1144: NetApp HCI AI Inferencing at the Edge Data Center with H615c and NVIDIA T4](https://docs.netapp.com/us-en/hci-solutions/hciaiedge_nva-1144_netapp_hci_ai_inferencing_at_the_edge_data_center_with_h615c_and_t4.html)

Please review the graphics in this document. Several of them come from PowerPoint decks and contain "NetApp CONFIDENTIAL" notations. These should not appear.

**Comment by ntap-bmegan** [comment]
@netapp-chandaj - Can you assign someone to review the images in the hci-solutions repo and list all that contain a confidential or other classification?

**Comment by ntap-bmegan** [comment]
@netapp-dorianh - Who handles the images for this repo? There are three, possibly four, that need to be updated. @netapp-chandaj has posted the list in the preceding comment. I checked the media folder and see only PNGs, no editable versions.

**Comment by ntap-bmegan** [comment]
@netapp-dorianh - Any update on the editable source for these images?

**Comment by ntap-bmegan** [comment]
@netapp-dorianh - We need to get this resolved. If the images are to remain, editable source either needs to be located or it needs to be created.

**Comment by netapp-dorianh** [comment]
I should be able to crop out the offending text on the images in the repo. I will take care of it shortly.

**Comment by netapp-dorianh** [comment]
I cropped the offending text out of the four images indicated above. Please let me know if you need anything else.
