### ISSUE TITLE
404'd URLs to TR/NVA docs

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/hci-solutions#54]
Top 3 links in Containers and Virtualization menu (image) all result in 404. Maybe there are similar issues on other pages. I don't know if this is related to the recent changes to built-in PDF reader for the Web site or from before...

![image](https://user-images.githubusercontent.com/16622642/97027785-d56a0800-158d-11eb-81bd-5f09df96d090.png)

Page: [NVA-1149: NetApp HCI for Red Hat OpenShift on Red Hat Virtualization](https://docs.netapp.com/us-en/hci-solutions/redhat_openshift_solution_overview__netapp_hci_for_red_hat_openshift_on_rhv.html)

**Comment by kevin-hoke** [comment]
Are you still seeing this issue?  I tried it on the public version and all of the links seemed to work.

**Comment by scaleoutsean** [comment]
All 3 work now, thank you!
