### ISSUE TITLE
possible stray page

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/hci-solutions#64]
Page: [](https://docs.netapp.com/us-en/hci-solutions/hciaiedge_.html)

This page exists but probably shouldn't? It's causing a blank spot in the sidebar. 

**Sidebar**
![image](https://user-images.githubusercontent.com/56453501/158580763-b608b68b-8443-4498-83d7-801156431480.png)

Note the position marker is between two entries. 

**Source**
![image](https://user-images.githubusercontent.com/56453501/158580640-2aaa5a87-bbe0-4c18-a301-4ab48a87dcd4.png)

https://github.com/NetAppDocs/hci-solutions/blob/main/project.yml#L331

**Comment by ntap-bmegan** [comment]
Interesting - the generated link for the page in the new issue template didn't work. The URL is:

https://docs.netapp.com/us-en/hci-solutions/hciaiedge_.html

**Comment by ntap-bmegan** [comment]
@netapp-dorianh - You were the last person to work in this repo. Can you either handle this issue or assign it appropriately? Tks.

**Comment by ntap-bmegan** [comment]
@netapp-dorianh & @netapp-ehoffman - This issues is being tracked for Q1, which ends in two weeks. We need someone to assign this issue to. If nobody has been assigned by 29 jul, we will have Wipro complete the work and publish the updates.

**Comment by netapp-dorianh** [comment]
Closed issue with necessary changes.
