### ISSUE TITLE
Images not rendering on page

### ISSUE THREAD

**Issue by Grantglass** [NetAppDocs/hci-solutions#67]
Page: [5. Deploy and Configure the F5 Big-IP Virtual Edition Appliance](https://docs.netapp.com/us-en/hci-solutions/anthos_task_deploy_the_f5_big-ip.html)

Under points 15 and 16 there are images that aren't rendered on the page.

**Comment by ntap-bmegan** [comment]
For whoever takes this issue...

I've opened a development issue against image references through includes. If your instance is through an include, no further action is needed on this issue.

**Comment by ac-ntap** [comment]
Ref-67 pushed to public repo.
