### ISSUE TITLE
Please add Language Filter for NVA-1141: NetApp HCI with Anthos, design and deployment

### ISSUE THREAD

**Issue by yukakou** [NetAppDocs/hci-solutions#68]
Page: [NVA-1141: NetApp HCI with Anthos, design and deployment](https://docs.netapp.com/us-en/hci-solutions/anthos_concept_overview.html)

I found that the language filter is missing on this page for NVA-1141: NetApp HCI with Anthos, design and deployment. Can you please fix?

**Comment by netapp-gudugunti** [comment]
Thanks! for the query, @yukakou. Per our discussion, since the filters are disabled by design, closing the ticket.
